<?php

namespace App\Exports;

use App\Models\Report;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class ReportExport implements FromArray, WithColumnWidths, WithHeadings, WithStyles, WithTitle
{
    public function __construct(
        private Report $report,
        private array $data,
    ) {}

    public function array(): array
    {
        $rows = $this->data['rows'] ?? [];

        if (isset($this->data['summary'])) {
            array_unshift(
                $rows,
                ['Male Count', $this->data['summary']['male_count'] ?? 0],
                ['Female Count', $this->data['summary']['female_count'] ?? 0],
                []
            );
        }

        if ($this->report->type === 'Financial' && isset($this->data['total'])) {
            $rows[] = [];
            $rows[] = ['', '', '', 'TOTAL', '₱ '.number_format($this->data['total'], 2)];
        }

        return $rows;
    }

    public function headings(): array
    {
        return $this->data['headers'] ?? [];
    }

    public function title(): string
    {
        return substr($this->report->type, 0, 31);
    }

    public function styles(Worksheet $sheet): array
    {
        $lastCol = $sheet->getHighestColumn();

        // Insert 3 header rows above the data
        $sheet->insertNewRowBefore(1, 3);

        $sheet->mergeCells("A1:{$lastCol}1");
        $sheet->setCellValue('A1', 'LGU GINGOOG CITY — OFFICE OF THE CITY AGRICULTURIST');

        $sheet->mergeCells("A2:{$lastCol}2");
        $sheet->setCellValue('A2', strtoupper($this->report->title));

        $sheet->mergeCells("A3:{$lastCol}3");
        $sheet->setCellValue('A3',
            'Period: '.\Carbon\Carbon::parse($this->report->period_from)->format('M d, Y').
            ' – '.\Carbon\Carbon::parse($this->report->period_to)->format('M d, Y').
            '  |  Generated by: '.$this->report->generated_by
        );

        return [
            1 => [
                'font' => ['bold' => true, 'size' => 13],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            2 => [
                'font' => ['bold' => true, 'size' => 11],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            3 => [
                'font' => ['size' => 9, 'color' => ['rgb' => '555555']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            4 => [
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '2D6A4F'],
                ],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
        ];
    }

    public function columnWidths(): array
    {
        return [
            'A' => 25, 'B' => 20, 'C' => 20,
            'D' => 25, 'E' => 18, 'F' => 18, 'G' => 18,
        ];
    }
}
