<?php

namespace App\Exports;

use App\Models\Report;
use Carbon\Carbon;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class ReportExport implements FromArray, WithColumnWidths, WithDrawings, WithHeadings, WithStyles, WithTitle
{
    private const REPORT_TIMEZONE = 'Asia/Manila';

    public function __construct(
        private Report $report,
        private array $data,
    ) {}

    public function array(): array
    {
        $rows = $this->data['rows'] ?? [];

        if (isset($this->data['summary'])) {
            array_unshift(
                $rows,
                ['Male Count', $this->data['summary']['male_count'] ?? 0],
                ['Female Count', $this->data['summary']['female_count'] ?? 0],
                []
            );
        }

        if ($this->report->type === 'Financial' && isset($this->data['total'])) {
            $rows[] = [];
            $rows[] = ['', '', '', 'TOTAL', 'PHP '.number_format($this->data['total'], 2)];
        }

        return $rows;
    }

    public function headings(): array
    {
        return $this->data['headers'] ?? [];
    }

    public function title(): string
    {
        return substr($this->report->module ?: $this->report->type, 0, 31);
    }

    public function drawings(): array
    {
        $logoPath = public_path('report-logo.png');

        if (!file_exists($logoPath)) {
            return [];
        }

        $drawing = new Drawing();
        $drawing->setName('LGU Gingoog City Agriculture logo');
        $drawing->setDescription('LGU Gingoog City Agriculture logo');
        $drawing->setPath($logoPath);
        $drawing->setHeight(72);
        $drawing->setCoordinates('A1');
        $drawing->setOffsetX(10);
        $drawing->setOffsetY(8);

        return [$drawing];
    }

    public function styles(Worksheet $sheet): array
    {
        $lastCol = $sheet->getHighestColumn();
        $headerLastCol = Coordinate::stringFromColumnIndex(
            max(Coordinate::columnIndexFromString($lastCol), 5)
        );

        // Insert report header rows above the data.
        $sheet->insertNewRowBefore(1, 5);

        $sheet->mergeCells("B1:{$headerLastCol}2");
        $sheet->setCellValue('B1', 'LGU GINGOOG CITY - OFFICE OF THE CITY AGRICULTURIST');

        $sheet->mergeCells("B3:{$headerLastCol}3");
        $sheet->setCellValue('B3', strtoupper($this->report->title));

        $sheet->mergeCells("B4:{$headerLastCol}4");
        $sheet->setCellValue('B4',
            'Type: '.$this->report->type.
            ' | Period: '.Carbon::parse($this->report->period_from)->format('M d, Y').
            ' - '.Carbon::parse($this->report->period_to)->format('M d, Y').
            ' | Generated by: '.$this->report->generated_by.
            ' | Date: '.$this->formattedReportGeneratedAt()
        );

        $sheet->getRowDimension(1)->setRowHeight(42);
        $sheet->getRowDimension(2)->setRowHeight(34);

        return [
            1 => [
                'font' => ['bold' => true, 'size' => 13],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            ],
            3 => [
                'font' => ['bold' => true, 'size' => 11],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            4 => [
                'font' => ['size' => 9, 'color' => ['rgb' => '555555']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            6 => [
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '2D6A4F'],
                ],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
        ];
    }

    public function columnWidths(): array
    {
        return [
            'A' => 25, 'B' => 20, 'C' => 20,
            'D' => 25, 'E' => 18, 'F' => 18, 'G' => 18,
        ];
    }

    private function formattedGeneratedAt(): string
    {
        return Carbon::now(self::REPORT_TIMEZONE)
            ->format('M d, Y, h:i A');
    }

    private function formattedReportGeneratedAt(): string
    {
        return Carbon::parse($this->report->generated_at)
            ->timezone(self::REPORT_TIMEZONE)
            ->format('M d, Y, h:i A');
    }
}

