<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1a1a1a; padding: 24px; }

  .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #2D6A4F; padding-bottom: 12px; }
  .header .agency { font-size: 11px; font-weight: bold; color: #2D6A4F; text-transform: uppercase; letter-spacing: 1px; }
  .header .title  { font-size: 15px; font-weight: bold; text-transform: uppercase; margin: 4px 0; }
  .header .meta   { font-size: 9px; color: #555; }

  table { width: 100%; border-collapse: collapse; margin-top: 14px; }
  thead tr { background-color: #2D6A4F; color: #fff; }
  th { padding: 7px 8px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
  tr:nth-child(even) td { background-color: #f9fafb; }

  .totals-row td { font-weight: bold; border-top: 2px solid #2D6A4F; background: #f0fdf4; }

  .footer { margin-top: 24px; font-size: 9px; color: #888; }
  .no-data { text-align: center; padding: 24px; color: #888; font-style: italic; }
  .summary { margin-top: 10px; font-size: 9px; color: #555; }
</style>
</head>
<body>

  <div class="header">
    <div class="agency">LGU Gingoog City &mdash; Office of the City Agriculturist</div>
    <div class="title">{{ $report->title }}</div>
    <div class="meta">
      Type: {{ $report->type }} &nbsp;|&nbsp;
      Period: {{ \Carbon\Carbon::parse($report->period_from)->format('M d, Y') }} &ndash; {{ \Carbon\Carbon::parse($report->period_to)->format('M d, Y') }} &nbsp;|&nbsp;
      Generated by: {{ $report->generated_by }} &nbsp;|&nbsp;
      Date: {{ \Carbon\Carbon::parse($report->generated_at)->format('M d, Y h:i A') }}
    </div>
    @if($report->notes)
    <div class="meta" style="margin-top:4px; font-style:italic;">Notes: {{ $report->notes }}</div>
    @endif
  </div>

  @if(empty($data['rows']))
    <div class="no-data">No records found for the selected period.</div>
  @else
    <table>
      <thead>
        <tr>
          @foreach($data['headers'] as $header)
            <th>{{ $header }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach($data['rows'] as $row)
          <tr>
            @foreach($row as $cell)
              <td>{{ $cell }}</td>
            @endforeach
          </tr>
        @endforeach

        @if($report->type === 'Financial' && isset($data['total']))
          <tr class="totals-row">
            <td colspan="{{ count($data['headers']) - 2 }}"></td>
            <td><strong>TOTAL</strong></td>
            <td>&#8369; {{ number_format($data['total'], 2) }}</td>
          </tr>
        @endif
      </tbody>
    </table>

    <div class="summary">Total records: {{ count($data['rows']) }}</div>
  @endif

  <div class="footer">
    LGU Gingoog City Agriculture Office &nbsp;|&nbsp; Generated: {{ now()->format('M d, Y h:i A') }}
  </div>

</body>
</html>
