<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, DejaVu Sans, sans-serif; font-size: 9px; color: #1a1a1a; padding: 24px; }

  .header { margin-bottom: 20px; border-bottom: 2px solid #2D6A4F; padding-bottom: 12px; }
  .header-table { width: 100%; border: 0; margin: 0; border-collapse: collapse; }
  .header-table td { border: 0; padding: 0; background: transparent; vertical-align: middle; }
  .header-logo-cell { width: 96px; text-align: left; }
  .header-spacer-cell { width: 96px; }
  .header-text-cell { text-align: center; }
  .header .logo { display: block; width: auto; height: 76px; }
  .header .agency { font-size: 11px; font-weight: bold; color: #2D6A4F; text-transform: uppercase; letter-spacing: 1px; }
  .header .title  { font-size: 15px; font-weight: bold; text-transform: uppercase; margin: 4px 0; }
  .header .meta   { font-size: 9px; color: #555; }

  table { width: 100%; border-collapse: collapse; margin-top: 14px; border: 1px solid #d1d5db; table-layout: fixed; }
  thead tr { background-color: #2D6A4F; color: #fff; }
  th { padding: 7px 8px; border: 1px solid #d1d5db; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 6px 8px; border: 1px solid #d1d5db; vertical-align: top; word-wrap: break-word; overflow-wrap: break-word; }
  tr:nth-child(even) td { background-color: #f9fafb; }

  .totals-row td { font-weight: bold; border-top: 2px solid #2D6A4F; background: #f0fdf4; }

  .footer { margin-top: 24px; font-size: 9px; color: #888; }
  .no-data { text-align: center; padding: 24px; color: #888; font-style: italic; }
  .summary { margin-top: 10px; font-size: 9px; color: #555; }
  .nursery-matrix-table { border-collapse: collapse; width: 100%; table-layout: auto; margin-top: 14px; }
  .nursery-matrix-table th, .nursery-matrix-table td { border: 1px solid #d1d5db; vertical-align: middle; }
  .act-header   { text-align: left; font-weight: bold; font-size: 9pt; background: #2D6A4F; color: #fff; min-width: 155px; padding: 7px 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  .site-header  { text-align: center; font-weight: bold; font-size: 10pt; background: #2D6A4F; color: #fff; padding: 7px 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  .crop-header  { text-align: center; font-weight: bold; font-size: 7.5px; background: #2D6A4F; color: #fff; min-width: 55px; word-break: break-word; padding: 6px 4px; text-transform: uppercase; }
  .total-header { text-align: center; font-weight: bold; font-size: 9pt; background: #2D6A4F; color: #fff; min-width: 55px; padding: 7px 6px; text-transform: uppercase; letter-spacing: 0.5px; }
  .act-cell   { text-align: left; font-size: 8.5px; padding: 7px 9px; }
  .num-cell   { text-align: center; font-size: 9px; padding: 6px 5px; }
  .total-cell { text-align: center; font-weight: bold; font-size: 9px; padding: 6px 5px; background: #f0fdf4; }
  .grand-row td { font-weight: bold; background: #f0fdf4; border-top: 2px solid #2D6A4F; font-size: 9px; text-align: center; padding: 7px 5px; }
  .grand-label  { text-align: left !important; padding-left: 9px !important; }
  .summary-grid { margin-top: 12px; width: 100%; }
  .summary-grid td { border: 1px solid #d1d5db; padding: 8px; background: #f8fafc; }
  .summary-label { font-size: 8px; text-transform: uppercase; color: #6b7280; }
  .summary-value { font-size: 14px; font-weight: bold; color: #2D6A4F; margin-top: 2px; }
</style>
</head>
<body>
  @php
    $reportTimezone = 'Asia/Manila';
    $generatedAt = now($reportTimezone);
    $reportGeneratedAt = \Carbon\Carbon::parse($report->generated_at)->timezone($reportTimezone);
    $logoPath = public_path('report-logo.png');
    $logoSrc = file_exists($logoPath)
      ? 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath))
      : null;
    $footerLabel = $footerLabel ?? 'Generated';
    $isNurseryProduction = $report->module === 'City Plant Nursery Production Records';
  @endphp

  <div class="header">
    <table class="header-table">
      <tr>
        <td class="header-logo-cell">
          @if($logoSrc)
            <img class="logo" src="{{ $logoSrc }}" alt="LGU Gingoog City Agriculture logo">
          @endif
        </td>
        <td class="header-text-cell">
          <div class="agency">LGU Gingoog City &mdash; Office of the City Agriculturist</div>
          <div class="title">{{ $report->title }}</div>
          <div class="meta">
            Type: {{ $report->type }} &nbsp;|&nbsp;
            Module: {{ $report->module }} &nbsp;|&nbsp;
            Period: {{ \Carbon\Carbon::parse($report->period_from)->format('M d, Y') }} &ndash; {{ \Carbon\Carbon::parse($report->period_to)->format('M d, Y') }} &nbsp;|&nbsp;
            Generated by: {{ $report->generated_by }} &nbsp;|&nbsp;
            Date: {{ $reportGeneratedAt->format('M d, Y, h:i A') }}
          </div>
          @if($report->notes)
          <div class="meta" style="margin-top:4px; font-style:italic;">Notes: {{ $report->notes }}</div>
          @endif
        </td>
        <td class="header-spacer-cell"></td>
      </tr>
    </table>
  </div>

  @if(isset($data['summary']))
    <table class="summary-grid">
      <tbody>
        <tr>
          <td>
            <div class="summary-label">Male Count</div>
            <div class="summary-value">{{ $data['summary']['male_count'] ?? 0 }}</div>
          </td>
          <td>
            <div class="summary-label">Female Count</div>
            <div class="summary-value">{{ $data['summary']['female_count'] ?? 0 }}</div>
          </td>
        </tr>
      </tbody>
    </table>
  @endif

  @if(empty($data['rows']))
    <div class="no-data">No records found for the selected period.</div>
  @elseif($isNurseryProduction)
    @php
      $nurseryHeaders  = $data['headers'] ?? [];
      $nurseryCropCols = array_slice($nurseryHeaders, 1, -1);
      $nurseryRows     = $data['rows'] ?? [];
      $siteLabel       = strtoupper($data['site_label'] ?? 'NURSERY SITE');

      $colTotals  = array_fill(0, count($nurseryCropCols), 0.0);
      $grandTotal = 0.0;
      foreach ($nurseryRows as $row) {
          $lastIdx = count($row) - 1;
          foreach ($row as $ci => $cell) {
              $numVal = (float) str_replace(',', '', $cell);
              if ($ci >= 1 && $ci < $lastIdx) {
                  $colTotals[$ci - 1] += $numVal;
              }
              if ($ci === $lastIdx) {
                  $grandTotal += $numVal;
              }
          }
      }
      $fmtNum = fn($v) => $v > 0 ? number_format($v, fmod($v, 1.0) === 0.0 ? 0 : 2) : '';
    @endphp
    <table class="nursery-matrix-table">
      <thead>
        <tr>
          <th rowspan="2" class="act-header">ACTIVITIES</th>
          <th colspan="{{ count($nurseryCropCols) }}" class="site-header">{{ $siteLabel }}</th>
          <th rowspan="2" class="total-header">TOTAL</th>
        </tr>
        <tr>
          @foreach($nurseryCropCols as $crop)
            <th class="crop-header">{{ $crop }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach($nurseryRows as $ri => $row)
          <tr>
            @foreach($row as $ci => $cell)
              @if($ci === 0)
                <td class="act-cell">{{ ($ri + 1) . '. ' . $cell }}</td>
              @elseif($ci === count($row) - 1)
                <td class="total-cell">{{ $cell }}</td>
              @else
                <td class="num-cell">{{ $cell }}</td>
              @endif
            @endforeach
          </tr>
        @endforeach
        <tr class="grand-row">
          <td class="grand-label">TOTAL</td>
          @foreach($colTotals as $colTotal)
            <td>{{ $fmtNum($colTotal) }}</td>
          @endforeach
          <td>{{ $fmtNum($grandTotal) }}</td>
        </tr>
      </tbody>
    </table>
  @else
    <table>
      <thead>
        <tr>
          @foreach($data['headers'] as $header)
            <th>{{ $header }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach($data['rows'] as $row)
          <tr>
            @foreach($row as $cell)
              <td>{{ $cell }}</td>
            @endforeach
          </tr>
        @endforeach

        @if($report->type === 'Financial' && isset($data['total']))
          <tr class="totals-row">
            <td colspan="{{ count($data['headers']) - 2 }}"></td>
            <td><strong>TOTAL</strong></td>
            <td>&#8369; {{ number_format($data['total'], 2) }}</td>
          </tr>
        @endif
      </tbody>
    </table>

    <div class="summary">Total records: {{ count($data['rows']) }}</div>
  @endif

  <div class="footer">
    LGU Gingoog City Agriculture Office &nbsp;|&nbsp; {{ $footerLabel }}: {{ $generatedAt->format('M d, Y h:i A') }}
  </div>

</body>
</html>



